name: Docker Build and Push

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: your-aws-region
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build Docker image
      run: docker build -t your-image-name .

    - name: Get branch name
      id: branch-name
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}

    - name: Tag Docker image with branch name
      run: |
        docker tag your-image-name:latest your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:${{ steps.branch-name.outputs.branch }}

    - name: Push Docker image to ECR
      run: docker push your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:${{ steps.branch-name.outputs.branch }}
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
