name: ecr_docker_deployment
on:
  push: {}  
  workflow_dispatch:  
    inputs:
      tag:
        description: 'Tag for the Docker image'
        required: false
        default: 'latest'        

jobs:
  docker_cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: petclinic-backend-img-cicd
          IMAGE_TAG: ${{ github.event.inputs.tag }}
        run: |
          if [["${{ github.event_name }}" == "push" ]];
          then
            IMAGE_TAG = "${{github.sha}}"
          else
            IMAGE_TAG = "${{ github.event.inputs.tag }}"
          fi
          
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .        
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
