name: ecr_docker_deployment
on: [push]
jobs:
  docker_cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

   - name: Build Docker image
      run: docker build -t your-image-name .

    - name: Get branch name
      id: branch-name
      run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}

    - name: Tag Docker image with branch name
      run: |
        docker tag your-image-name:latest your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:${{ steps.branch-name.outputs.branch }}

    - name: Push Docker image to ECR
      run: docker push your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:${{ steps.branch-name.outputs.branch }}
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
