name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: eu-central-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push Docker image to ECR
      run: |
        docker build -t petclinic-backend-img-cicd .
        docker tag petclinic-backend-img-cicd:latest GitHub.dkr.ecr.your-aws-region.amazonaws.com/petclinic-backend-img-cicd:latest
        docker push your-aws-account-id.dkr.ecr.your-aws-region.amazonaws.com/your-repository-name:latest
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
